# Generated by Django 5.1.15 on 2026-03-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_projectmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="task_distribution",
            field=models.CharField(
                choices=[
                    ("auto", "Automatic task distribution"),
                    ("manual", "Manual task assignment"),
                ],
                default="auto",
                help_text="How tasks are distributed: auto assigns to all members, manual requires explicit assignment",
                max_length=20,
            ),
        ),
    ]
